[versions]
gradle = "7.4.2"
kotlin = "1.8.20"
compose = "1.4.1"
composeActivity = "1.7.2"
appCompat = "1.6.1"
androidxCore = "1.10.1"

[libraries]
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidX-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = { id = "com.android.application", version.ref = "gradle" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nativeCocoapod = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }